#!/usr/bin/env python3
"""
YouTube Upload Script Generator
Run this utility once to configure your account and generate the upload script.
"""

import os
import stat

UPLOAD_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""
YouTube Video Uploader (with GUI)
Generated by generate_uploader.py
Drop this script in any folder with video files and run it.
"""

import os
import sys
import glob
import pickle
import shutil
import threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox

# ── CONFIG (set by generator) ──────────────────────────────────────────────
YOUTUBE_CLIENT_SECRETS = "CLIENT_SECRETS_PATH_PLACEHOLDER"
DEFAULT_SAVE_DEST = "DEFAULT_SAVE_DEST_PLACEHOLDER"   # "" means no default
TOKEN_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "youtube_token.pickle")
VIDEO_EXTENSIONS = [".mp4", ".mov", ".avi", ".mkv", ".wmv", ".flv", ".webm", ".m4v"]

# ── DEPENDENCY CHECK ───────────────────────────────────────────────────────
try:
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request
except ImportError:
    import subprocess
    print("Installing required dependencies...")
    subprocess.check_call([sys.executable, "-m", "pip", "install",
        "google-api-python-client", "google-auth-oauthlib", "google-auth-httplib2"])
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

BG     = "#0d0d0d"
CARD   = "#161616"
ACCENT = "#ff3c3c"
FG     = "#f0f0f0"
MUTED  = "#666666"
ENTRY  = "#1a1a1a"
BORDER = "#2a2a2a"


def authenticate():
    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, "rb") as f:
            creds = pickle.load(f)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(YOUTUBE_CLIENT_SECRETS, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, "wb") as f:
            pickle.dump(creds, f)
    return build("youtube", "v3", credentials=creds)


def find_videos(folder):
    videos = []
    for ext in VIDEO_EXTENSIONS:
        videos.extend(glob.glob(os.path.join(folder, f"*{ext}")))
        videos.extend(glob.glob(os.path.join(folder, f"*{ext.upper()}")))
    return sorted(set(videos))


# ── PRIVACY TOGGLE WIDGET ──────────────────────────────────────────────────

class PrivacyToggle(tk.Frame):
    """
    A segmented toggle button for Private / Unlisted / Public.
    Selected segment lights up; others stay dark.
    """
    OPTIONS = ["Private", "Unlisted", "Public"]
    VALUES  = ["private", "unlisted", "public"]

    def __init__(self, parent, **kwargs):
        super().__init__(parent, bg=ENTRY, **kwargs)
        self._var = tk.StringVar(value="private")
        self._buttons = []

        self.configure(highlightthickness=1, highlightbackground=BORDER)

        for i, (label, val) in enumerate(zip(self.OPTIONS, self.VALUES)):
            btn = tk.Label(
                self,
                text=label,
                font=("Helvetica", 10, "bold"),
                padx=18, pady=8,
                cursor="hand2",
                relief="flat",
            )
            btn.grid(row=0, column=i, sticky="nsew")
            self.grid_columnconfigure(i, weight=1)

            # Separator line between segments
            if i < len(self.OPTIONS) - 1:
                sep = tk.Frame(self, bg=BORDER, width=1)
                sep.grid(row=0, column=i, sticky="nse")

            btn.bind("<Button-1>", lambda e, v=val: self._select(v))
            self._buttons.append((btn, val))

        self._refresh()

    def _select(self, value):
        self._var.set(value)
        self._refresh()

    def _refresh(self):
        current = self._var.get()
        for btn, val in self._buttons:
            if val == current:
                btn.configure(bg=ACCENT, fg="white")
            else:
                btn.configure(bg=ENTRY, fg=MUTED)

    def get(self):
        return self._var.get()


# ── VIDEO INFO DIALOG ──────────────────────────────────────────────────────

class VideoInfoDialog(tk.Toplevel):
    """Dialog to collect description, thumbnail, and privacy for one video."""

    def __init__(self, parent, video_path, index, total):
        super().__init__(parent)
        self.result = None
        self.video_path = video_path
        self.title_str = os.path.splitext(os.path.basename(video_path))[0]
        self._thumb_path = None

        self.title(f"Video {index} of {total}")
        self.resizable(False, False)
        self.grab_set()
        self.configure(bg=BG)

        self._build(index, total)
        self.update_idletasks()

        w, h = 560, 520
        x = (self.winfo_screenwidth() - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")
        self.resizable(True, True)
        self.wait_window()

    def _label(self, parent, text):
        tk.Label(parent, text=text, bg=BG, fg=MUTED,
                 font=("Helvetica", 8, "bold"), anchor="w").pack(fill="x", pady=(0, 3))

    def _build(self, index, total):
        # Top accent bar
        tk.Frame(self, bg=ACCENT, height=3).pack(fill="x")

        # Header
        header = tk.Frame(self, bg=BG, pady=14)
        header.pack(fill="x", padx=28)
        tk.Label(header, text=f"{index} / {total}",
                 bg=BG, fg=ACCENT, font=("Helvetica", 9, "bold")).pack(anchor="w")
        tk.Label(header, text=self.title_str,
                 bg=BG, fg=FG, font=("Helvetica", 15, "bold"),
                 wraplength=500, anchor="w").pack(fill="x")

        # Divider
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")

        # Body
        body = tk.Frame(self, bg=BG, padx=28, pady=18)
        body.pack(fill="both", expand=True)

        # Description
        self._label(body, "DESCRIPTION")
        self.desc_box = tk.Text(body, height=4, bg=ENTRY, fg=FG,
                                insertbackground=FG, relief="flat",
                                font=("Helvetica", 11), padx=10, pady=8,
                                highlightthickness=1, highlightbackground=BORDER,
                                highlightcolor=ACCENT)
        self.desc_box.pack(fill="x", pady=(0, 16))

        # Thumbnail
        self._label(body, "THUMBNAIL")
        thumb_row = tk.Frame(body, bg=BG)
        thumb_row.pack(fill="x", pady=(0, 16))

        self.thumb_label = tk.Label(
            thumb_row, text="No thumbnail selected",
            bg=ENTRY, fg=MUTED, font=("Helvetica", 10),
            anchor="w", padx=10, relief="flat",
            highlightthickness=1, highlightbackground=BORDER
        )
        self.thumb_label.pack(side="left", fill="x", expand=True, ipady=7)

        tk.Button(
            thumb_row, text="Browse…", bg=ACCENT, fg="white",
            font=("Helvetica", 10, "bold"), relief="flat",
            padx=14, cursor="hand2", activebackground="#cc2222",
            activeforeground="white", command=self._browse_thumb
        ).pack(side="left", padx=(8, 0), ipady=7)

        # Privacy toggle
        self._label(body, "VISIBILITY")
        self.privacy_toggle = PrivacyToggle(body)
        self.privacy_toggle.pack(fill="x", pady=(0, 16))

        # Save destination
        self._label(body, "MOVE VIDEO TO (optional)")
        save_row = tk.Frame(body, bg=BG)
        save_row.pack(fill="x", pady=(0, 0))

        self._save_dest = tk.StringVar(value=DEFAULT_SAVE_DEST)
        self.save_label = tk.Label(
            save_row, textvariable=self._save_dest,
            bg=ENTRY, fg=(FG if DEFAULT_SAVE_DEST else MUTED), font=("Helvetica", 10),
            anchor="w", padx=10, relief="flat",
            highlightthickness=1, highlightbackground=BORDER
        )
        self.save_label.pack(side="left", fill="x", expand=True, ipady=7)

        tk.Button(
            save_row, text="Browse…", bg=CARD, fg=FG,
            font=("Helvetica", 10, "bold"), relief="flat",
            padx=14, cursor="hand2", activebackground=BORDER,
            activeforeground=FG, command=self._browse_save_dest
        ).pack(side="left", padx=(8, 0), ipady=7)

        tk.Button(
            save_row, text="✕", bg=CARD, fg=MUTED,
            font=("Helvetica", 10), relief="flat",
            padx=8, cursor="hand2", activebackground=BORDER,
            activeforeground=FG,
            command=lambda: [
                self._save_dest.set(DEFAULT_SAVE_DEST),
                self.save_label.configure(fg=(FG if DEFAULT_SAVE_DEST else MUTED))
            ]
        ).pack(side="left", padx=(4, 0), ipady=7)

        # Divider
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")

        # Footer buttons
        footer = tk.Frame(self, bg=BG, padx=28, pady=14)
        footer.pack(fill="x")

        tk.Button(
            footer, text="Skip", bg=CARD, fg=MUTED,
            font=("Helvetica", 10), relief="flat", padx=16,
            cursor="hand2", activebackground=BORDER,
            command=self._skip
        ).pack(side="left")

        tk.Button(
            footer, text="Add to Queue →", bg=ACCENT, fg="white",
            font=("Helvetica", 11, "bold"), relief="flat", padx=20,
            cursor="hand2", activebackground="#cc2222",
            activeforeground="white", command=self._confirm
        ).pack(side="right")

    def _browse_thumb(self):
        path = filedialog.askopenfilename(
            title="Select Thumbnail",
            filetypes=[("Images", "*.jpg *.jpeg *.png *.gif *.bmp"), ("All files", "*.*")]
        )
        if path:
            self._thumb_path = path
            self.thumb_label.configure(text=os.path.basename(path), fg=FG)

    def _browse_save_dest(self):
        folder = filedialog.askdirectory(title="Choose folder to save a copy of the video")
        if folder:
            self._save_dest.set(folder)
            self.save_label.configure(fg=FG)

    def _confirm(self):
        thumb = self._thumb_path
        if thumb and not os.path.exists(thumb):
            messagebox.showwarning("Thumbnail not found",
                f"Could not find:\n{thumb}\nProceeding without thumbnail.")
            thumb = None
        save_dest = self._save_dest.get().strip() or None
        if save_dest and not os.path.isdir(save_dest):
            messagebox.showwarning("Folder not found",
                f"Save destination not found:\n{save_dest}\nThe copy will be skipped.")
            save_dest = None
        self.result = {
            "title":       self.title_str,
            "description": self.desc_box.get("1.0", "end").strip(),
            "thumbnail":   thumb,
            "privacy":     self.privacy_toggle.get(),
            "filepath":    self.video_path,
            "save_dest":   save_dest,
        }
        self.destroy()

    def _skip(self):
        self.result = None
        self.destroy()


# ── UPLOAD PROGRESS WINDOW ─────────────────────────────────────────────────

class UploadWindow(tk.Tk):
    def __init__(self, queue):
        super().__init__()
        self.queue = queue
        self.results = []

        self.configure(bg=BG)
        self.title("YouTube Uploader")
        self.resizable(False, False)

        w, h = 580, 500
        x = (self.winfo_screenwidth() - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")

        self._build()
        self.after(400, self._start_uploads)

    def _build(self):
        tk.Frame(self, bg=ACCENT, height=3).pack(fill="x")

        header = tk.Frame(self, bg=BG, pady=16)
        header.pack(fill="x", padx=28)
        tk.Label(header, text="UPLOADING TO YOUTUBE",
                 bg=BG, fg=ACCENT, font=("Helvetica", 11, "bold")).pack(anchor="w")
        self.status_label = tk.Label(header, text="Starting...",
                                     bg=BG, fg=FG, font=("Helvetica", 12))
        self.status_label.pack(anchor="w", pady=(4, 0))

        # Progress bar
        prog_frame = tk.Frame(self, bg=BG, padx=28)
        prog_frame.pack(fill="x")

        style = ttk.Style()
        style.theme_use("clam")
        style.configure("YT.Horizontal.TProgressbar",
                        troughcolor=ENTRY, background=ACCENT,
                        bordercolor=ENTRY, lightcolor=ACCENT, darkcolor=ACCENT)
        self.progress = ttk.Progressbar(prog_frame, style="YT.Horizontal.TProgressbar",
                                        mode="determinate")
        self.progress.pack(fill="x", pady=(0, 4))

        self.pct_label = tk.Label(prog_frame, text="0%", bg=BG, fg=MUTED,
                                  font=("Helvetica", 9), anchor="e")
        self.pct_label.pack(fill="x")

        tk.Frame(self, bg=BORDER, height=1).pack(fill="x", pady=(10, 0))

        # Log
        log_outer = tk.Frame(self, bg=BG, padx=28, pady=16)
        log_outer.pack(fill="both", expand=True)

        log_frame = tk.Frame(log_outer, bg=CARD,
                             highlightthickness=1, highlightbackground=BORDER)
        log_frame.pack(fill="both", expand=True)

        self.log = tk.Text(log_frame, bg=CARD, fg=FG, font=("Courier New", 9),
                           relief="flat", state="disabled", padx=12, pady=10)
        sb = tk.Scrollbar(log_frame, command=self.log.yview, bg=CARD)
        self.log.configure(yscrollcommand=sb.set)
        sb.pack(side="right", fill="y")
        self.log.pack(fill="both", expand=True)

    def _log(self, msg):
        self.log.configure(state="normal")
        self.log.insert("end", msg + "\n")
        self.log.see("end")
        self.log.configure(state="disabled")

    def _set_progress(self, pct):
        self.progress["value"] = pct
        self.pct_label.configure(text=f"{pct}%")
        self.update_idletasks()

    def _start_uploads(self):
        threading.Thread(target=self._upload_all, daemon=True).start()

    def _upload_all(self):
        self._log("Authenticating with YouTube...")
        try:
            youtube = authenticate()
            self._log("✓ Authenticated\n")
        except Exception as e:
            self._log(f"✗ Auth failed: {e}")
            self.after(0, self.status_label.configure, {"text": "Authentication failed."})
            return

        total = len(self.queue)
        for i, info in enumerate(self.queue, 1):
            fname = os.path.basename(info["filepath"])
            self.after(0, self.status_label.configure,
                       {"text": f"Uploading {i} of {total}: {info['title']}"})
            self._log(f"── {fname}  [{info['privacy']}]")
            self.after(0, self._set_progress, 0)

            try:
                video_id = self._upload_one(youtube, info)
                self._log(f"   ✓ https://youtu.be/{video_id}\n")
                self.results.append((fname, video_id, "success"))
            except Exception as e:
                self._log(f"   ✗ {e}\n")
                self.results.append((fname, None, str(e)))

        self.after(0, self.status_label.configure,
                   {"text": f"Done — {total} video(s) processed."})
        self.after(0, self._set_progress, 100)
        self._log("─" * 46)
        self._log("SUMMARY")
        for fname, vid_id, status in self.results:
            if vid_id:
                self._log(f"  ✓  {fname}")
                self._log(f"     https://youtu.be/{vid_id}")
            else:
                self._log(f"  ✗  {fname}  →  {status}")

    def _upload_one(self, youtube, info):
        body = {
            "snippet": {
                "title": info["title"],
                "description": info["description"],
                "categoryId": "22",
            },
            "status": {"privacyStatus": info["privacy"]},
        }
        media = MediaFileUpload(info["filepath"], chunksize=-1, resumable=True)
        request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                pct = int(status.progress() * 100)
                self.after(0, self._set_progress, pct)

        video_id = response["id"]

        if info.get("thumbnail"):
            try:
                youtube.thumbnails().set(
                    videoId=video_id,
                    media_body=MediaFileUpload(info["thumbnail"])
                ).execute()
                self._log("   ✓ Thumbnail uploaded")
            except Exception as e:
                self._log(f"   ⚠ Thumbnail failed: {e}")

        if info.get("save_dest"):
            try:
                dest_folder = info["save_dest"]
                filename = os.path.basename(info["filepath"])
                dest_path = os.path.join(dest_folder, filename)
                # Avoid overwriting an existing file by appending a counter
                base, ext = os.path.splitext(filename)
                counter = 1
                while os.path.exists(dest_path):
                    dest_path = os.path.join(dest_folder, f"{base} ({counter}){ext}")
                    counter += 1
                shutil.move(info["filepath"], dest_path)
                self._log(f"   ✓ Moved → {dest_path}")
            except Exception as e:
                self._log(f"   ⚠ Save copy failed: {e}")

        return video_id


# ── MAIN ───────────────────────────────────────────────────────────────────

def main():
    folder = os.path.dirname(os.path.abspath(__file__))
    videos = find_videos(folder)

    if not videos:
        root = tk.Tk()
        root.withdraw()
        messagebox.showinfo("No Videos Found", f"No video files found in:\n{folder}")
        return

    root = tk.Tk()
    root.withdraw()

    queue = []
    for i, vpath in enumerate(videos, 1):
        dialog = VideoInfoDialog(root, vpath, i, len(videos))
        if dialog.result:
            queue.append(dialog.result)

    root.destroy()

    if not queue:
        print("No videos queued. Exiting.")
        return

    app = UploadWindow(queue)
    app.mainloop()


if __name__ == "__main__":
    main()
'''


def print_header():
    print("""
╔══════════════════════════════════════════════════════╗
║         YouTube Upload Script Generator              ║
╚══════════════════════════════════════════════════════╝
""")


def get_client_secrets_path():
    print("── Step 1: Google OAuth Credentials ──────────────────────")
    print("You need a client_secrets.json from Google Cloud Console.")
    print()
    print("To get one:")
    print("  1. Go to https://console.cloud.google.com")
    print("  2. Create a project (or select existing)")
    print("  3. Enable 'YouTube Data API v3'")
    print("  4. Go to APIs & Services > Credentials")
    print("  5. Create OAuth 2.0 Client ID (Desktop app)")
    print("  6. Download the JSON file")
    print()
    path = input("Path to your client_secrets.json: ").strip()
    path = os.path.expanduser(path)
    if not os.path.exists(path):
        print(f"\nWARNING: File not found at {path}")
        print("The script will still be generated — make sure the file")
        print("exists at that path before running the upload script.")
        input("\nPress Enter to continue...")
    return path


def get_default_save_dest():
    print("\n── Step 3: Default Save Destination ──────────────────────")
    print("After each video uploads, the script can automatically move")
    print("it to a folder on your computer (e.g. an archive or backup).")
    print("Users can still override this per-video in the GUI.")
    print()
    path = input("Default folder to move videos to (leave blank to skip): ").strip()
    if not path:
        print("  ↳ No default set — users can still choose per-video in the GUI.")
        return ""
    path = os.path.expanduser(path)
    if not os.path.isdir(path):
        print(f"\nWARNING: Folder not found at {path}")
        print("The script will still be generated — make sure the folder")
        print("exists before running the upload script.")
        input("\nPress Enter to continue...")
    else:
        print(f"  ✓ Default save destination: {path}")
    return path


def check_dependencies():
    print("\n── Step 2: Checking Dependencies ─────────────────────────")
    try:
        import googleapiclient
        import google_auth_oauthlib
        print("✓ All dependencies already installed.")
    except ImportError:
        print("Installing dependencies...")
        import subprocess, sys
        subprocess.check_call([sys.executable, "-m", "pip", "install",
            "google-api-python-client", "google-auth-oauthlib", "google-auth-httplib2"])
        print("✓ Dependencies installed.")


def generate_script(client_secrets_path, default_save_dest, output_path):
    script_content = UPLOAD_SCRIPT_TEMPLATE.replace(
        "CLIENT_SECRETS_PATH_PLACEHOLDER", client_secrets_path
    ).replace(
        "DEFAULT_SAVE_DEST_PLACEHOLDER", default_save_dest
    )
    with open(output_path, "w") as f:
        f.write(script_content)
    st = os.stat(output_path)
    os.chmod(output_path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    print(f"\n✓ Upload script generated: {output_path}")


def main():
    print_header()
    print("This utility generates a YouTube upload script you can drop")
    print("into any folder with videos to batch upload them.\n")

    client_secrets_path = get_client_secrets_path()
    check_dependencies()
    default_save_dest = get_default_save_dest()

    print("\n── Step 4: Output Location ────────────────────────────────")
    default_output = os.path.join(os.getcwd(), "upload_to_youtube.py")
    output = input(f"Save upload script to [{default_output}]: ").strip()
    if not output:
        output = default_output
    output = os.path.expanduser(output)

    generate_script(client_secrets_path, default_save_dest, output)

    save_note = (f"  Default move folder: {default_save_dest}"
                 if default_save_dest else
                 "  No default move folder set (choose per-video in the GUI)")

    print(f"""
╔══════════════════════════════════════════════════════╗
║                    ALL DONE!                         ║
╚══════════════════════════════════════════════════════╝

How to use your generated upload script:
  1. Copy upload_to_youtube.py into any folder with videos
  2. Run: python upload_to_youtube.py
  3. A GUI window opens for each video:
       - Type a description
       - Click Browse to pick a thumbnail
       - Click the Private / Unlisted / Public toggle
       - Optionally change the save destination
       - Click "Add to Queue" or "Skip"
  4. First run opens a browser to log in to YouTube
  5. Token is saved — no login needed after that

{save_note}
Supported formats: mp4, mov, avi, mkv, wmv, flv, webm, m4v
""")


if __name__ == "__main__":
    main()
